# Generated by Django 5.2.14 on 2026-05-05 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True)),
                ('hq', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_kubricon_competitor', models.BooleanField(default=False)),
                ('relevance_to_kubricon', models.TextField(blank=True, help_text='Why this portfolio company matters as a thesis-fit signal')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True)),
                ('hq_country', models.CharField(blank=True, max_length=80)),
                ('hq_city', models.CharField(blank=True, max_length=120)),
                ('aum_text', models.CharField(blank=True, help_text='Free-form, e.g. $500M AUM', max_length=120)),
                ('check_min_usd', models.PositiveBigIntegerField(blank=True, null=True)),
                ('check_max_usd', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tier', models.CharField(choices=[('S', 'Tier S - direct thesis fit'), ('1', 'Tier 1 - broad AI'), ('2', 'Tier 2 - pre-seed friendly'), ('watch', 'Watch list')], default='watch', max_length=10)),
                ('stages', models.JSONField(blank=True, default=list, help_text="List of stages, e.g. ['pre-seed','seed','A']")),
                ('thesis_summary', models.TextField(blank=True)),
                ('portfolio_notes', models.TextField(blank=True, help_text='Comparable bets in our category, e.g. led Runway Series B')),
                ('internal_notes', models.TextField(blank=True)),
                ('last_activity_at', models.DateField(blank=True, help_text='Date of most recent known investment', null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('openvc', 'OpenVC'), ('sec_edgar', 'SEC EDGAR'), ('crunchbase', 'Crunchbase'), ('signal_nfx', 'Signal NFX'), ('twitter', 'Twitter / X'), ('referral', 'Referral'), ('other', 'Other')], default='manual', max_length=20)),
                ('source_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('thesis', 'Thesis'), ('category', 'Category')], default='thesis', max_length=16)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('revenue', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['processed', '-created_at'], name='investors_c_process_2b693a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_usd', models.PositiveBigIntegerField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, help_text='e.g. Pre-seed, Seed, Series A', max_length=40)),
                ('announced_at', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='investors.company')),
            ],
            options={
                'ordering': ['-announced_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_lead', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investors.deal')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investors.fund')),
            ],
            options={
                'ordering': ['-deal__announced_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('body', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, help_text='Partner / Principal / Founder / Angel / ...', max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_status', models.CharField(choices=[('unknown', 'Unknown'), ('verified', 'Verified'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed')], default='unknown', max_length=20)),
                ('twitter_handle', models.CharField(blank=True, help_text='Without @', max_length=80)),
                ('linkedin_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('bio_short', models.TextField(blank=True)),
                ('pipeline_stage', models.CharField(choices=[('identified', 'Identified'), ('researched', 'Researched'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('meeting', 'Meeting booked'), ('dd', 'Due diligence'), ('term_sheet', 'Term sheet'), ('closed_won', 'Closed - committed'), ('closed_lost', 'Closed - passed'), ('passed', 'Passed (no fit)')], default='identified', max_length=20)),
                ('pipeline_changed_at', models.DateTimeField(blank=True, null=True)),
                ('warmth', models.CharField(choices=[('cold', 'Cold'), ('warm_2nd', 'Warm (2nd-degree)'), ('warm_1st', 'Warm (1st-degree)')], default='cold', max_length=10)),
                ('internal_notes', models.TextField(blank=True)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='investors.fund')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='fund',
            name='thesis_tags',
            field=models.ManyToManyField(blank=True, related_name='funds', to='investors.tag'),
        ),
        migrations.AddField(
            model_name='company',
            name='category_tags',
            field=models.ManyToManyField(blank=True, related_name='companies', to='investors.tag'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('snoozed', 'Snoozed')], default='open', max_length=10)),
                ('body', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('related_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='investors.fund')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='investors.person')),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['announced_at'], name='investors_d_announc_9d9e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['stage'], name='investors_d_stage_2a5684_idx'),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.UniqueConstraint(fields=('fund', 'deal'), name='uniq_fund_deal'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['content_type', 'object_id'], name='investors_n_content_895fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['pipeline_stage'], name='investors_p_pipelin_342b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['warmth'], name='investors_p_warmth_1db08d_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['email_status'], name='investors_p_email_s_1e676c_idx'),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['tier'], name='investors_f_tier_3202ea_idx'),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['last_activity_at'], name='investors_f_last_ac_dcf906_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'due_date'], name='investors_t_status_612542_idx'),
        ),
    ]
