# Generated by Django 5.2.14 on 2026-05-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('openvc', 'OpenVC'), ('sec_edgar', 'SEC EDGAR'), ('crunchbase', 'Crunchbase'), ('signal_nfx', 'Signal NFX'), ('twitter', 'Twitter / X'), ('github_awesome', 'GitHub awesome list'), ('newsletter', 'Newsletter'), ('referral', 'Referral'), ('other', 'Other')], default='manual', max_length=20),
        ),
    ]
