# Generated by Django 5.2.14 on 2026-05-05 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_expand_fund_source_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(blank=True, help_text='URL captured alongside the company name (usually the company website)')),
                ('source_label', models.CharField(default='github_awesome', help_text='Where this mention was harvested from', max_length=40)),
                ('raw_text', models.CharField(blank=True, help_text='Original text fragment that produced the mention', max_length=300)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_by_funds', to='investors.company')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_mentions', to='investors.fund')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fund'], name='investors_p_fund_id_6a61d5_idx'), models.Index(fields=['company'], name='investors_p_company_b4013a_idx')],
                'constraints': [models.UniqueConstraint(fields=('fund', 'company'), name='uniq_fund_company_mention')],
            },
        ),
    ]
