# Generated by Django 5.2.14 on 2026-05-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_add_portfolio_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='General inbound / pitch email if published.', max_length=254),
        ),
        migrations.AddField(
            model_name='fund',
            name='submission_url',
            field=models.URLField(blank=True, help_text='URL where this fund accepts pitches (e.g. /connect, /submit).'),
        ),
    ]
