# Generated by Django 5.2.14 on 2026-05-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_fund_contact_email_fund_submission_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='next_followup_at',
            field=models.DateTimeField(blank=True, help_text='When to nudge again if no reply by then.', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='outreach_channel',
            field=models.CharField(blank=True, choices=[('', '—'), ('form', 'Submission form'), ('email', 'Email'), ('li_dm', 'LinkedIn DM'), ('x_dm', 'X / Twitter DM'), ('intro', 'Warm intro'), ('other', 'Other')], default='', help_text='Channel used for the most recent outbound contact.', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='outreach_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='outreach_text',
            field=models.TextField(blank=True, help_text='Verbatim copy of the most recent message sent.'),
        ),
        migrations.AddField(
            model_name='person',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['outreach_sent_at'], name='investors_p_outreac_ca1b97_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['next_followup_at'], name='investors_p_next_fo_866369_idx'),
        ),
    ]
