# Generated by Django 5.2.14 on 2026-05-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_person_next_followup_at_person_outreach_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[('', 'Unassigned'), ('igor', 'Igor'), ('partner', 'Partner'), ('shared', 'Both / shared')], default='', help_text='Who owns outreach to this person (Igor / partner / shared).', max_length=10),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['assigned_to'], name='investors_p_assigne_302313_idx'),
        ),
    ]
