# Generated by Django 5.2.14 on 2026-05-07 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0006_person_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('', '—'), ('form', 'Submission form'), ('email', 'Email'), ('li_dm', 'LinkedIn DM'), ('x_dm', 'X / Twitter DM'), ('intro', 'Warm intro'), ('other', 'Other')], help_text='Which channel was used.', max_length=10)),
                ('direction', models.CharField(choices=[('out', 'Outbound'), ('in', 'Reply received')], default='out', max_length=4)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_events_recorded', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_events', to='investors.person')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['person', 'channel'], name='investors_o_person__342bf8_idx'), models.Index(fields=['-sent_at'], name='investors_o_sent_at_739e15_idx')],
            },
        ),
    ]
