# Generated by Django 5.2.14 on 2026-05-05 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('provider', models.CharField(choices=[('vertex', 'Vertex AI'), ('openai', 'OpenAI')], max_length=16)),
                ('model', models.CharField(max_length=80)),
                ('task', models.CharField(choices=[('score_fund', 'Score fund'), ('smart_tag_fund', 'Smart-tag fund'), ('extract_company', 'Extract company'), ('extract_person', 'Extract person'), ('draft_outreach', 'Draft outreach email'), ('other', 'Other')], default='other', max_length=32)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('prompt_text', models.TextField(blank=True)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('response_text', models.TextField(blank=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('cached', 'Cached'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error_text', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='ingest.importrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['input_hash'], name='llm_llmcall_input_h_284d84_idx'), models.Index(fields=['task', '-created_at'], name='llm_llmcall_task_bea6dc_idx'), models.Index(fields=['provider', 'model'], name='llm_llmcall_provide_d9b5fc_idx'), models.Index(fields=['content_type', 'object_id'], name='llm_llmcall_content_23161f_idx')],
                'constraints': [models.UniqueConstraint(fields=('input_hash', 'provider', 'model', 'task'), name='uniq_llm_call_input')],
            },
        ),
    ]
