# Generated by Django 5.2.14 on 2026-05-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcall',
            name='task',
            field=models.CharField(choices=[('score_fund', 'Score fund'), ('smart_tag_fund', 'Smart-tag fund'), ('extract_company', 'Extract company'), ('categorize_company', 'Categorize company'), ('extract_person', 'Extract person'), ('draft_outreach', 'Draft outreach email'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
