# Generated by Django 5.2.14 on 2026-05-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_alter_llmcall_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcall',
            name='task',
            field=models.CharField(choices=[('score_fund', 'Score fund'), ('smart_tag_fund', 'Smart-tag fund'), ('extract_company', 'Extract company'), ('categorize_company', 'Categorize company'), ('extract_person', 'Extract person'), ('extract_partners', 'Extract fund partners'), ('find_submission_form', 'Find submission form'), ('draft_outreach', 'Draft outreach email'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
