# Generated by Django 5.2.14 on 2026-05-05 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(db_index=True, max_length=40)),
                ('command', models.CharField(blank=True, max_length=120)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='running', max_length=12)),
                ('rows_seen', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True, help_text='Tail of stdout / errors for quick review in admin')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='ingest_impo_source_898569_idx'), models.Index(fields=['status'], name='ingest_impo_status_7d7e48_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=40)),
                ('external_id', models.CharField(max_length=255)),
                ('object_id', models.PositiveBigIntegerField()),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['source', 'external_id'], name='ingest_exte_source_021ad4_idx'), models.Index(fields=['content_type', 'object_id'], name='ingest_exte_content_927d78_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_external_ref')],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(db_index=True, max_length=40)),
                ('kind', models.CharField(choices=[('unmatched_filer', 'Unmatched filer / fund'), ('new_deal_hint', 'Possible new deal'), ('partner_post', 'Partner social post'), ('new_portfolio_hit', 'Portfolio company hit'), ('other', 'Other')], max_length=32)),
                ('summary', models.CharField(help_text='Human-readable one-liner for the admin list view', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw data from the source (filer name, RSS entry, tweet body...)')),
                ('fired_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the source observed the signal')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('promoted', 'Promoted'), ('ignored', 'Ignored')], default='new', max_length=12)),
                ('operator_note', models.TextField(blank=True)),
                ('suggested_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_signals', to='investors.company')),
                ('suggested_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_signals', to='investors.fund')),
                ('suggested_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_signals', to='investors.person')),
            ],
            options={
                'ordering': ['-fired_at'],
                'indexes': [models.Index(fields=['status', '-fired_at'], name='ingest_sign_status_cb2a28_idx'), models.Index(fields=['kind', 'status'], name='ingest_sign_kind_d2a82b_idx')],
            },
        ),
    ]
